#+TITLE: [c]hecklist
#+OPTIONS: H:2 TOC:1 view:showall

A Haskell [c]hecklist. For starting off, rebooting, or just tidying things up.

* Changes

The initial Haskell [c]hecklist was released around ghc-8.10, and, at time of writing, ghc-9.8.1 is in `ghcup list`.

The checklist now concentrates on a cabal-style workflow. I personally no longer use stack and would be concerned that any stack-based advice would become stale. Stack is also, in my opinion, a complete workflow compared with cabal where gaps remain.

The use of templates has been abandoned in favour of `cabal new`, with advice and snippets around additions.

The combination of emacs org-mode and Haskell development has progressed, and for even more bespokity, I have switched to haskell-ng.

Developments surrounding cabal are in a state of flux, and, until stability, I use cabal-fix for my cabal file needs.

* Quick Start

To quickly install Haskell, follow the instructions at [[https://www.haskell.org/ghcup/][GHCup]].

To quickly create a new Haskell project, run `cabal init` interactively or:

#+begin_src sh :results output
mkdir xyzzy
cd xyzzy
cabal init --simple --overwrite --libandexe --tests --language=GHC2021 --license=BSD-2-Clause  -p xyzzy
#+end_src

A quick test of these installations is to compile and test the project using cabal:

#+begin_src sh :results output
cabal build && cabal install && cabal test
#+end_src

* Tools

Setup of a modern Haskell environment is straight forward. [[https://www.haskell.org/ghcup/][ghcup]] takes care of ghc, cabal, stack & the haskell-language-server. ~cabal~ can then be used to install other tools.

** [[https://www.haskell.org/ghcup/][ghcup-managed tools]]

#+begin_src sh :results output
ghcup list -c set -r
#+end_src

#+RESULTS:
: ghc 9.8.1 latest,base-4.19.0.0 hls-powered,2023-10-09
: cabal 3.10.2.0 latest
: hls 2.5.0.0 latest
: stack 2.13.1 latest
: ghcup 0.1.20.0 latest,recommended

=ghcup= places everything in ~/.ghcup/bin

#+begin_src sh :results output :exports both
which cabal
#+end_src

#+RESULTS:
: /Users/tonyday567/.ghcup/bin/cabal


Haskell-language-server versions matching older GHC versions are also installed, and selected automatically.

#+begin_src sh :results output :exports both
haskell-language-server-wrapper --version
#+end_src

#+RESULTS:
: haskell-language-server version: 2.5.0.0 (GHC: 9.2.8) (PATH: /Users/tonyday567/.ghcup/hls/2.5.0.0/lib/haskell-language-server-2.5.0.0/bin/haskell-language-server-wrapper)

** installing tools

- [[https://hackage.haskell.org/package/hlint][hlint]]
- [[https://hackage.haskell.org/package/ormolu][ormolu]]
- [[https://hackage.haskell.org/package/hkgr][hkgr]]

#+begin_src sh
cabal install ormolu hlint hkgr --allow-newer --overwrite-policy=always
#+end_src

~cabal~ stores executables in ​~​/.cabal/bin, ~stack~ in ​~​/.local/bin.

#+begin_src sh :results output :exports both
which hlint
#+end_src

#+RESULTS:
: /Users/tonyday567/.cabal/bin/hlint

** Haskell CI

GitHub actions are the current and common practice for continuous integration of projects. The current checklist CI uses actions from [[https://github.com/haskell-actions/][haskell-actions]].

** cabal-docspec

cabal-extras is a github repo that contains cabal-centric tools to help with builds and development. From these, I would recommend cabal-docspec.

[[https://github.com/phadej/cabal-extras/blob/master/cabal-docspec/MANUAL.md][cabal-docspec]] is a doctest runner that exists as a process outside the specification of a cabal project, acting more like hlint then a separate cabal stanza.

#+begin_src sh
git clone https://github.com/phadej/cabal-extras
cd cabal-extras/cabal-docspec
cabal install cabal-docspec:exe:cabal-docspec --overwrite-policy=always
#+end_src

** Doom emacs

Haskell setup for [[https://github.com/hlissner/doom-emacs#install][Doom]] emacs is straight-forward.

in ~~/.config/doom/init.el~, uncomment the haskell line and add lsp:

#+begin_src elisp
(haskell +lsp)      ; a language that's lazier than I am
#+end_src

in ~/.config/doom/config.el~, place any personal config preferences. Mine are:

#+begin_src elisp
;; haskell
;;
(after! haskell
  (setq
   haskell-font-lock-symbols t
   haskell-interactive-popup-errors nil
   lsp-enable-folding nil
   lsp-response-timeout 120
   lsp-ui-sideline-enable nil           ; not anymore useful than flycheck
   lsp-ui-doc-enable nil                ; slow and redundant with K
   lsp-modeline-diagnostics-scope :project
   +lsp-prompt-to-install-server 'quiet
   flycheck-check-syntax-automatically '(save)
   lsp-haskell-brittany-on nil
   lsp-haskell-floskell-on nil
   lsp-haskell-fourmolu-on nil
   lsp-haskell-stylish-haskell-on nil
   lsp-haskell-retrie-on nil
   haskell-process-show-debug-tips nil
   haskell-process-suggest-remove-import-lines nil
   haskell-process-suggest-restart nil
   haskell-process-type 'cabal-repl
   )
  (global-so-long-mode -1)
  ;; makes underscore an alphanumeric
  (add-hook! 'haskell-mode-hook (modify-syntax-entry ?_ "w"))
)
#+end_src

* checklist


[[https://hackage.haskell.org/package/mealy]]
[[https://github.com/tonyday567/mealy]]

- [ ] version check&bump

  #+begin_src sh :results output
  cd ~/haskell/mealy
  #+end_src

  0.4.4.1
- [ ] ghcup upgrades

  #+begin_src sh :results output
  ghcup list -c set -r
  #+end_src

  #+RESULTS:
  : ghc 9.8.1 latest,base-4.19.0.0 hls-powered,2023-10-09
  : cabal 3.10.2.0 latest
  : hls 2.5.0.0 latest
  : stack 2.13.1 latest
  : ghcup 0.1.20.0 latest,recommended
- [ ] cabal.project check

  #+begin_src sh :results output
  cat cabal.project
  #+end_src

  #+RESULTS:
  : packages:
  :   mealy.cabal
- [ ] upstream publishings
- [ ] cabal update

  #+begin_src sh :results output
  cabal update
  #+end_src

  #+RESULTS:
  : Downloading the latest package list from hackage.haskell.org
  : Package list of hackage.haskell.org has been updated.
  : The index-state is set to 2023-12-19T03:05:53Z.
  : To revert to previous state run:
  :     cabal v2-update 'hackage.haskell.org,2023-12-18T22:41:30Z'
- [ ] cabal outdated
    #+begin_src sh :results output
    cabal outdated
    #+end_src

    #+RESULTS:
    : Outdated dependencies:
    : primitive >=0.7.2 && <0.9 (latest: 0.9.0.0)
- [ ] cabal gen-bounds
    #+begin_src sh :results output
    cabal gen-bounds
    #+end_src

    #+RESULTS:
    : Resolving dependencies...
    : Congratulations, all your dependencies have upper bounds!
- [ ] cabal build --ghc-options=-Wunused-packages
    #+begin_src sh :results output
    cabal clean && cabal build --ghc-options=-Wunused-packages
    #+end_src

    #+RESULTS:
    : Up to date
- [ ] cabal-fix

    #+begin_src sh :results output
    cabal-fix --gen
    #+end_src

    #+begin_src sh :results output
    cabal-fix -f ~/haskell/cabal-fix/my-cabal-fix.config
    #+end_src

    #+RESULTS:
    : Nothing

    #+begin_src sh :results output
    cabal-fix -i
    #+end_src

    #+RESULTS:
- [ ] cabal build --prefer-oldest

    #+begin_src sh :results output
    cabal build --prefer-oldest
    #+end_src
- [ ] FIXMEs & TODOs
- [ ] pragma cleanup
- [ ] cabal-docspec

    #+begin_src sh :results output
    cabal-docspec
    #+end_src

    #+RESULTS:
- [ ] cabal install
    #+begin_src sh :results output
    cabal install
    #+end_src
- [ ] cabal test
    #+begin_src sh :results output
    cabal test
    #+end_src
- [ ] cabal bench
    #+begin_src sh :results output
    cabal bench
    #+end_src

    #+RESULTS:
    #+begin_example
    Build profile: -w ghc-9.8.1 -O1
    In order, the following will be built (use -v for more details):
     - perf-0.12.0.1 (bench:perf-bench) (ephemeral targets)
    Preprocessing benchmark 'perf-bench' for perf-0.12.0.1..
    Building benchmark 'perf-bench' for perf-0.12.0.1..
    [1 of 1] Compiling Main             ( app/bench.hs, /Users/tonyday/haskell/perf/dist-newstyle/build/x86_64-osx/ghc-9.8.1/perf-0.12.0.1/b/perf-bench/build/perf-bench/perf-bench-tmp/Main.o )
    [1 of 2] Compiling Main             ( app/bench.hs, /Users/tonyday/haskell/perf/dist-newstyle/build/x86_64-osx/ghc-9.8.1/perf-0.12.0.1/b/perf-bench/build/perf-bench/perf-bench-tmp/Main.o )
    [2 of 2] Linking /Users/tonyday/haskell/perf/dist-newstyle/build/x86_64-osx/ghc-9.8.1/perf-0.12.0.1/b/perf-bench/build/perf-bench/perf-bench [Objects changed]
    Running 1 benchmarks...
    Benchmark perf-bench: RUNNING...
    label1          label2          old result      new result      change

    sum             time            1.38e4          1.85e4          degraded
    Benchmark perf-bench: ERROR
    #+end_example
- [ ] ormolu

  #+begin_src sh :results output
  ormolu --mode check $(git ls-files '*.hs')
  #+end_src

  #+RESULTS:

  #+begin_src sh :results output
  ormolu --mode inplace $(git ls-files '*.hs')
  #+end_src

  #+RESULTS:
- [ ] hlint
  #+begin_src sh :results output
  hlint .
  #+end_src

  #+RESULTS:
  : No hints
- [ ] CI upgrade

  - check tested-with line in cabal file
- [ ] exact version bump
  0.4.4.1
- [ ] branch, push & check CI
- [ ] haddock

  #+begin_src sh :results output
  cabal haddock
  #+end_src
- [ ] readme
- [ ] magit range
- [ ] ChangeLog
- [ ] PR to main
- [ ] merge PR
- [ ] immediate checkout and pull main
- [ ] final check

  #+begin_src sh :results output
  cabal clean && cabal build && cabal-docspec
  #+end_src
- [ ] hkgr tagdist

  #+begin_src sh :results output
  hkgr tagdist
  #+end_src

  #+RESULTS:
  : v0.12.0.1
  : Running hlint
  : Wrote tarball sdist to /Users/tonyday/haskell/perf/.hkgr/perf-0.12.0.1.tar.gz
- [ ] hkgr publish

  #+begin_src sh :results output
  hkgr tagdist
  #+end_src
- [ ] check Hackage
        Sometimes haddocks don't build on Hackage. Here's a recipe for uploading your own docs.

        #+begin_src sh
        cabal haddock --builddir=docs --haddock-for-hackage --enable-doc
        cabal upload -d --publish docs/*-docs.tar.gz
        #+end_src

* extra Files
** readme.md

Practice varies widely, from saying nothing to all documentation being in the readme. This readme.md template:

- adds some badges for Hackage & CI.
- Includes a short description and basic Usage example, which in many cases should be exactly repeated in the cabal file as synopsis and description stanzas.

#+begin_src org :tangle readme.md
{{name}}
===

[![Hackage](https://img.shields.io/hackage/v/{{name}}.svg)](https://hackage.haskell.org/package/{{name}})
[![Build Status](https://github.com/{{github-username}}/{{name}}/workflows/haskell-ci/badge.svg)](https://github.com/{{github-username}}/{{name}}/actions?query=workflow%3Ahaskell-ci)

`{{name}}` is a new package.

Usage
==

``` haskell
import {{#lib-name}}{{lib-name}}{{#lib-name2}}.{{lib-name2}}{{/lib-name2}}{{/lib-name}}{{^lib-name}}Lib{{/lib-name}}
```
#+end_src


readmes can be included as documentation within a cabal file like so:

#+begin_src sh :results output
extra-doc-files:
    ChangeLog.md
    readme.md
#+end_src

** readme.org

an alternative readme.

#+begin_src org :tangle readme.org
,* {{name}}

[[https://hackage.haskell.org/package/{{name}}][https://img.shields.io/hackage/v/{{name}}.svg]]
[[https://github.com/{{github-username}}/{{name}}/actions?query=workflow%3Ahaskell-ci][https://github.com/{{github-username}}/{{name}}/workflows/haskell-ci/badge.svg]]

~{{name}}~ is a new package.

,* Usage

,#+begin_src haskell :results output
import {{#lib-name}}{{lib-name}}{{#lib-name2}}.{{lib-name2}}{{/lib-name2}}{{/lib-name}}{{^lib-name}}Lib{{/lib-name}}
,#+end_src

,* Development

,#+begin_src haskell :results output
:set -Wno-type-defaults
:set -Wno-name-shadowing
:set -XOverloadedStrings
,#+end_src

check

,#+begin_src haskell :results output :export both
let x = "ok"
putStrLn x
,#+end_src

#+end_src


** .hlint.yaml

#+begin_src :tangle .hlint.yaml
- ignore: {name: Use if}
- ignore: {name: Use bimap}
- ignore: {name: Eta reduce}
- ignore: {name: Redundant fromInteger}
#+end_src

** .ghci

#+begin_src :tangle .ghci
:set -XRebindableSyntax
:set -XOverloadedStrings
:set -Wno-type-defaults
#+end_src

** .gitignore

#+begin_src org :tangle .gitignore
/.stack-work/
/dist-newstyle/
stack.yaml.lock
**/.DS_Store
cabal.project.local*
/.hie/
.ghc.environment.*
/.hkgr/
#+end_src

** .gitattributes

#+begin_src org :tangle .gitattributes
{-# START_FILE .gitattributes #-}
other/* linguist-documentation
#+end_src

** .projectile

In emacs, haskell-language-server uses projectile to discover the project root directory, which is indicated by an empty ~.projectile~ file.

#+begin_src org :tangle .projectile
#+end_src

** .github/workflows/haskell-ci.yml

This CI includes tests for ormolu, hlint, cabal-doctest and the usual cabal checks across a wide GHC range.

[[https://docs.github.com/en/actions][GitHub Actions Documentation - GitHub Docs]]

#+begin_src org :tangle .github/workflows/haskell-ci.yml
on: [push]
name: haskell-ci
jobs:
  hlint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: haskell-actions/hlint-setup@v2
    - uses: haskell-actions/hlint-run@v2
      with:
        path: .
        fail-on: warning
  ormolu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: haskell-actions/run-ormolu@v14
  cabal:
    name: GHC ${{ matrix.ghc-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        ghc-version: ['9.8', '9.6', '9.4', '9.2', '8.10']
        docspec: [false]
        experimental: [false]

        include:
          - os: windows-latest
            ghc-version: '9.6'
          - os: macos-latest
            ghc-version: '9.6'
          - os: ubuntu-latest
            ghc-version: '9.6'
            docspec: true
            experimental: true
            name: docspec

    steps:
      - uses: actions/checkout@v3

      - name: Set up GHC ${{ matrix.ghc-version }}
        uses: haskell-actions/setup@v2
        id: setup
        with:
          ghc-version: ${{ matrix.ghc-version }}

      - name: Installed minor versions of GHC and Cabal
        shell: bash
        run: |
          GHC_VERSION=$(ghc --numeric-version)
          CABAL_VERSION=$(cabal --numeric-version)
          echo "GHC_VERSION=${GHC_VERSION}"     >> "${GITHUB_ENV}"
          echo "CABAL_VERSION=${CABAL_VERSION}" >> "${GITHUB_ENV}"

      - name: Configure the build
        run: |
          cabal configure --enable-tests --enable-benchmarks --disable-documentation
          cabal build --dry-run
        # The last step generates dist-newstyle/cache/plan.json for the cache key.

      - name: Restore cached dependencies
        uses: actions/cache/restore@v3
        id: cache
        with:
          path: ${{ steps.setup.outputs.cabal-store }}
          key: ${{ runner.os }}-ghc-${{ env.GHC_VERSION }}-cabal-${{ env.CABAL_VERSION }}-plan-${{ hashFiles('**/plan.json') }}
          restore-keys: |
            ${{ runner.os }}-ghc-${{ env.GHC_VERSION }}-cabal-${{ env.CABAL_VERSION }}-

      - name: Install dependencies
        run: cabal build all --only-dependencies

      # Cache dependencies already here, so that we do not have to rebuild them should the subsequent steps fail.
      - name: Save cached dependencies
        uses: actions/cache/save@v3
        # Caches are immutable, trying to save with the same key would error.
        if: ${{ !steps.cache.outputs.cache-hit
          || steps.cache.outputs.cache-primary-key != steps.cache.outputs.cache-matched-key }}
        with:
          path: ${{ steps.setup.outputs.cabal-store }}
          key: ${{ steps.cache.outputs.cache-primary-key }}

      - name: Build
        run: cabal build all

      - name: Check cabal file
        run: cabal check

      - if: matrix.docspec
        name: cabal-docspec
        run: |
          mkdir -p $HOME/.cabal/bin
          echo "$HOME/.cabal/bin" >> $GITHUB_PATH
          curl -sL https://github.com/phadej/cabal-extras/releases/download/cabal-docspec-0.0.0.20230406/cabal-docspec-0.0.0.20230406-x86_64-linux.xz > cabal-docspec.xz
          echo '68fa9addd5dc453d533a74a763950499d4593b1297c9a05c3ea5bd1acc04c9dd cabal-docspec.xz' | sha256sum -c -
          xz -d < cabal-docspec.xz > $HOME/.cabal/bin/cabal-docspec
          rm -f cabal-docspec.xz
          chmod a+x $HOME/.cabal/bin/cabal-docspec
          $HOME/.cabal/bin/cabal-docspec --version
          cabal-docspec
#+end_src

* extra cabal stanzas

~cabal~ [[https://cabal.readthedocs.io/en/3.4/][docs]] have gotten very good of late, and these recommended stanzas should be read with those docs handy.

** ghc2021-stanza

This stanza reproduces the GHC2021 extensions for ghc's prior to 9.2.

#+begin_src org
common ghc2021-stanza
  if impl(ghc >=9.2)
    default-language:
      GHC2021
  if impl(ghc <9.2)
    default-language:
      Haskell2010
    default-extensions:
      BangPatterns
      BinaryLiterals
      ConstrainedClassMethods
      ConstraintKinds
      DeriveDataTypeable
      DeriveFoldable
      DeriveFunctor
      DeriveGeneric
      DeriveLift
      DeriveTraversable
      DoAndIfThenElse
      EmptyCase
      EmptyDataDecls
      EmptyDataDeriving
      ExistentialQuantification
      ExplicitForAll
      FlexibleContexts
      FlexibleInstances
      ForeignFunctionInterface
      GADTSyntax
      GeneralisedNewtypeDeriving
      HexFloatLiterals
      ImplicitPrelude
      InstanceSigs
      KindSignatures
      MonomorphismRestriction
      MultiParamTypeClasses
      NamedFieldPuns
      NamedWildCards
      NumericUnderscores
      PatternGuards
      PolyKinds
      PostfixOperators
      RankNTypes
      RelaxedPolyRec
      ScopedTypeVariables
      StandaloneDeriving
      StarIsType
      TraditionalRecordSyntax
      TupleSections
      TypeApplications
      TypeOperators
      TypeSynonymInstances
  if impl(ghc <9.2) && impl(ghc >=8.10)
    default-extensions:
      ImportQualifiedPost
      StandaloneKindSignatures
  -- but keeping ormolu happy
  if impl(ghc >=8.10)
    default-extensions:
      NoImportQualifiedPost
#+end_src

** ghc-options-stanza

#+begin_src org
common ghc-options-stanza
  ghc-options:
    -Wall
    -Wcompat
    -Wincomplete-record-updates
    -Wincomplete-uni-patterns
    -Wredundant-constraints
#+end_src

Stanzas are used like so:

#+begin_src org
library
  import: ghc2021-stanza
  import: ghc-options-stanza
#+end_src

** ghc-options-exe-stanza

#+begin_src org
common ghc-options-exe-stanza
    ghc-options:
        -fforce-recomp
        -funbox-strict-fields
        -rtsopts
        -threaded
        -with-rtsopts=-N
#+end_src

* org-mode notes

** setup

The [[https://orgmode.org/worg/org-contrib/babel/][babel]] functionality in org-mode is very old, and hasn't kept up with changes in haskell-mode practices. In particular, it uses the old haskell inferior mode to invoke ghci rather than the more modern haskell process methods. This could make it a touch fragile as it won't pick up standard configurations.

Using org-mode is particularly helpful in development loops where rebooting ghci requires a large amount of state. A complex function, say, with intermediate results can be laid out using org-mode and state-of-debugging sessions can evolve and be remembered between sessions.

It also works well as an alternative readme, with no gap between code blocks as basic tests and code blocks as usage documentation.

The babel functionality, ob-haskell, creates an ~inf-haskell~ buffer which is not the modern Haskell repl.

#+begin_src haskell
:set -XOverloadedStrings
:set -Wno-type-defaults
putStrLn "ok"
#+end_src

#+RESULTS:
: > > ok

** single session

Once a haskell code block is evaluated (eg ~C-c C-c~ in the above block), you can check in the ~*haskell*~ buffer to see input and output.

#+begin_src haskell
x = [0..4]
x
#+end_src

#+RESULTS:
| 0 | 1 | 2 | 3 | 4 |

babel feeds the code block in as single lines, returns the final computation as a result, and then tries to do some post-result format massaging, like putting the result into a table.

~:results output~ in the header of the block provides the raw output as you would expect from ghci.

#+begin_src haskell :results output
x = [0..4]
x
#+end_src

#+RESULTS:
:
: [0,1,2,3,4]

Note that double brackets will be interpreted by org-mode as a link, even inside a result section.

#+begin_src haskell :results output
x = [[0..4]]
x
#+end_src

** multi-line

Multi-line code blocks need ~:{~ ~:}~ wrappers.

#+begin_src haskell :results output
:{
t1 :: Bool -> Int
t1 z = case z of
        True -> 1
        False -> 0
:}

t1 True
#+end_src

#+RESULTS:
:
: > 1

** executable project

This is required if you are working with a project, and compiling a library doesn't suit. (Library is the default in emacs)

#+begin_src elisp
(setq haskell-process-args-cabal-repl '("poker-fold:exe:poker-fold-speed"))
#+end_src

* ToDo haskell-ng

I am experimenting with haskell-ng mode, a replacement for haskell-mode, which utilises tree-sitter.

* ToDo cabal-fix
